docker_image: "nsls2/linux-anvil-cos7-x86_64:latest"
env_name: "tomviz-{{ today }}-bld2"
conda_binary: "mamba"
python_version: "3.7"
pkg_name: "tomviz"
pkg_version: "1.10.0.post266"
extra_packages: "'databroker>=2.0.0b8' area-detector-handlers tomopy hxntools 'pyxrf>=1.0.17' 'dask=2022.1.1' 'distributed=2022.1.1'"
extra_cmd_after_install: "pip install itk-elastix xrf-tomo tiled[client]==0.1.0a70; conda list"
channels: "-c conda-forge"
